name: Rust

on: 
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: fmt check
      run: cargo fmt --check
    - name: clippy
      run: cargo clippy -- -Dwarnings
    - name: Build
      run: cargo build
    
